### ISSUE TITLE
Error with "Being John Malkovich" image

### ISSUE THREAD

**Issue by mathewrapid** [digiaonline/cuddly-potato#35] opened 2018-04-30 07:27 UTC
The `face_replace.py` outputs an error when processing the image 

![malkovich](https://user-images.githubusercontent.com/1784672/39418110-12095e30-4c61-11e8-9dff-0f2cd40bdb07.png)

```
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/ubuntu/cuddly-potato/face_replace/face_replace.py", line 305, in <module>
    args.boxes,
  File "/home/ubuntu/cuddly-potato/face_replace/face_replace.py", line 219, in detect
    l_img = paste_image(l_img, s_img, x, y, x2, y2)
  File "/home/ubuntu/cuddly-potato/face_replace/face_replace.py", line 65, in paste_image
    alpha_l * large[y1:y2, x1:x2, c])
ValueError: operands could not be broadcast together with shapes (65,51) (0,51
```

**Comment by hugovk** [comment] 2018-04-30 07:34
Duplicate of #34.

**Closed by hugovk** 2018-04-30 07:34 UTC
Labels: py
